name: Lighthouse

on:
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer dependences
        run: npm ci

      - name: Lighthouse
        run: npm run lighthouse
